using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:The file header is missing or not located at the top of the file", Justification = "Not needed in this app")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "Not needed in this app")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names must not begin with an underscore", Justification = "Stylistic choice")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "Stylistic choice")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1615:Element return value must be documented", Justification = "Most of the time it is straightforward")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1611:Element parameters must be documented", Justification = "Most of the time it is straightforward")]
[assembly: SuppressMessage("", "SA1027", Justification = "Stylistic choice")]
[assembly: SuppressMessage("", "CA2007", Justification = "Not needed systematically.")]
[assembly: SuppressMessage("", "CA1056", Justification = "Stylistic choice")]
[assembly: SuppressMessage("", "CA1054", Justification = "Stylistic choice")]
[assembly: SuppressMessage("", "CA2227", Justification = "API entities can have read-write collections")]
[assembly: SuppressMessage("", "CA1819", Justification = "API entities can return arrays")]
[assembly: SuppressMessage("", "CA1724", Justification = "Type name conflict reviewed")]
[assembly: SuppressMessage("", "CA1307", Justification = "Overload not present in netstandard")]
